name: echo_bazaar
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get: ^4.7.3
  flutter_svg: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg/
    - assets/png/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
  - family: Inter
    fonts:
      - asset: assets/fonts/inter/Inter_18pt-Bold.ttf
        weight: 700
      - asset: assets/fonts/inter/Inter_18pt-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/inter/Inter_18pt-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/inter/Inter_18pt-Light.ttf
        weight: 300
      - asset: assets/fonts/inter/Inter_18pt-Medium.ttf
        weight: 500
      - asset: assets/fonts/inter/Inter_18pt-Regular.ttf
        weight: 400
      - asset: assets/fonts/inter/Inter_18pt-SemiBold.ttf
        weight: 600
        
  - family: Sora
    fonts:
      - asset: assets/fonts/sora/Sora-Bold.ttf
        weight: 700
      - asset: assets/fonts/sora/Sora-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/sora/Sora-ExtraLight.ttf
        weight: 200
      - asset: assets/fonts/sora/Sora-Light.ttf
        weight: 300
      - asset: assets/fonts/sora/Sora-Medium.ttf
        weight: 500
      - asset: assets/fonts/sora/Sora-Regular.ttf
        weight: 400
      - asset: assets/fonts/sora/Sora-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/sora/Sora-Thin.ttf
        weight: 100